# Generated by Django 5.2.11 on 2026-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
